/**
 * Static entry point — do not edit this file directly.
 *
 * Switch exercises:   npm run tutorial <topic>
 * Then edit:          the path printed in the terminal
 *
 * This file re-exports whatever tutorial is currently active
 * via the auto-generated ./tutorial.jsx (or .tsx) pointer file.
 */
export { default } from './tutorial';
