// Auto-generated by `npm run tutorial` — do not edit.
// Edit the real file: phase-01-fundamentals/02-function-vs-class-components/tutorial.jsx
export { default } from '../../phase-01-fundamentals/02-function-vs-class-components/tutorial.jsx';
