// Auto-generated by `npm run tutorial` — do not edit.
// Edit the real file: phase-07-routing/08-url-state-vs-component-state/tutorial.jsx
export { default } from '../../phase-07-routing/08-url-state-vs-component-state/tutorial.jsx';
