// Auto-generated by `npm run tutorial` — do not edit.
// Edit the real file: phase-02-hooks/03-use-layout-effect/tutorial.jsx
export { default } from '../../phase-02-hooks/03-use-layout-effect/tutorial.jsx';
